name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/static_site

env:
  # 作業ディレクトリ
  WORK_DIR: sample/chart/app

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Astro app
        uses: actions/upload-artifact@v1
        with:
          path: ${{ env.WORK_DIR }}/dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
